# Generated by Django 5.2.3 on 2025-06-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_teacher_is_active_teacher_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
